`timescale 1ns/1ps

// ============================================================================
// Project      : SNN_ECG_V2
// Module       : npu
// Description  : Neuromorphic Processing Unit. Coordinates shared SRAM 
//                access between the neuron FSM and output reader, manages 
//                spike registration, and controls membrane update sequencing.
// Reference    : IEEE TBCAS 2022, Section IV-B "NPU With FSMs"
// ============================================================================

module npu #(
    parameter N_NEURON = 271,
    parameter N_MAX    = 1024,
    parameter V_WIDTH  = 8,
    parameter W_WIDTH  = 6,
    parameter ID_WIDTH = 10
)(
    input  wire                   clk,
    input  wire                   rst_n,
    input  wire                   spike_clear,

    // Mode control signals from top_fsm
    input  wire                   mode_wacc,
    input  wire                   mode_vcalcu,
    input  wire                   mode_output,

    // Synaptic inputs from weight_decode
    input  wire signed [W_WIDTH-1:0] weight_in,
    input  wire [ID_WIDTH-1:0]    dst_id,
    input  wire                   weight_valid,

    // Threshold parameter (fixed in silicon)
    input  wire signed [V_WIDTH-1:0] v_threshold,

    // Spike bus output (to spike_merge)
    output wire [N_MAX-1:0]       spike_bus,

    // Completion status handshakes
    output wire                   wacc_done,
    output wire                   vcalcu_done,
    output wire                   all_neurons_done,

    // Secondary SRAM access for classification read-out
    input  wire [ID_WIDTH-1:0]    or_ns_addr,
    input  wire                   or_ns_ce,
    output wire [V_WIDTH+W_WIDTH:0] or_ns_rdata
);

    localparam NS_WIDTH = V_WIDTH + W_WIDTH + 1;

    // ========================================================================
    // SRAM Arbitration
    // ========================================================================
    // Single-port SRAM shared between neuron_fsm and output_reader.
    // The controller (top_fsm) ensures mode_output is mutually exclusive.
    wire [ID_WIDTH-1:0] nfsm_ns_addr;
    wire                nfsm_ns_ce, nfsm_ns_we;
    wire [NS_WIDTH-1:0] nfsm_ns_wdata;
    wire [NS_WIDTH-1:0] ns_rdata;

    wire [ID_WIDTH-1:0] ns_addr   = mode_output ? or_ns_addr : nfsm_ns_addr;
    wire                ns_ce     = mode_output ? or_ns_ce   : nfsm_ns_ce;
    wire                ns_we     = mode_output ? 1'b0       : nfsm_ns_we;
    wire [NS_WIDTH-1:0] ns_wdata  = nfsm_ns_wdata;

    assign or_ns_rdata = ns_rdata;

    neuron_state_sram u_ns_sram (
        .clk   (clk),
        .ce    (ns_ce),
        .we    (ns_we),
        .addr  (ns_addr),
        .wdata (ns_wdata),
        .rdata (ns_rdata)
    );

    // ========================================================================
    // Neuron Pointer Generator
    // ========================================================================
    wire [ID_WIDTH-1:0] neuron_ptr;
    wire                nptr_valid;
    wire                ptr_done;
    wire                nfsm_ready;

    neuron_ptr_gen #(
        .N_NEURON (N_NEURON), 
        .ID_WIDTH (ID_WIDTH)
    ) u_ptr (
        .clk        (clk),
        .rst_n      (rst_n),
        .start      (mode_vcalcu),
        .ready      (nfsm_ready),
        .neuron_ptr (neuron_ptr),
        .valid      (nptr_valid),
        .done       (ptr_done)
    );

    assign all_neurons_done = ptr_done;

    // ========================================================================
    // Neuron Processing Engine
    // ========================================================================
    wire [ID_WIDTH-1:0] spike_id;
    wire                spike_valid_nfsm;

    neuron_fsm #(
        .V_WIDTH  (V_WIDTH),
        .W_WIDTH  (W_WIDTH),
        .ID_WIDTH (ID_WIDTH)
    ) u_nfsm (
        .clk          (clk),
        .rst_n        (rst_n),
        .mode_wacc    (mode_wacc),
        .mode_vcalcu  (mode_vcalcu),
        .ready        (nfsm_ready),
        .weight_in    (weight_in),
        .dst_id       (dst_id),
        .weight_valid (weight_valid),
        .neuron_ptr   (neuron_ptr),
        .nptr_valid   (nptr_valid),
        .v_threshold  (v_threshold),
        .ns_addr      (nfsm_ns_addr),
        .ns_ce        (nfsm_ns_ce),
        .ns_we        (nfsm_ns_we),
        .ns_wdata     (nfsm_ns_wdata),
        .ns_rdata     (ns_rdata),
        .spike_id     (spike_id),
        .spike_valid  (spike_valid_nfsm),
        .wacc_done    (wacc_done),
        .vcalcu_done  (vcalcu_done)
    );

    // ========================================================================
    // Spike Bus Registry
    // ========================================================================
    // Accumulates all spikes generated by the network in the current time step.
    reg [N_MAX-1:0] spike_reg;

    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            spike_reg <= {N_MAX{1'b0}};
        end else begin
            if (spike_clear) begin
                spike_reg <= {N_MAX{1'b0}};
            end else if (spike_valid_nfsm) begin
                // spike_id is guaranteed to be within [0, N_NEURON-1] range by neuron_fsm
                spike_reg[spike_id] <= 1'b1;
            end
        end
    end

    assign spike_bus = spike_reg;

endmodule
